org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

fpsmatch_version=1.3.0
fpsmatch_snapshot_tag=fpsmatch-1.20.1-1.3.0-forge-snapshot-20260916-1623
kotlin_forge_version=4.11.0
modernui_core_version=3.12.0
modernui_forge_version=3.12.0.1
tacz_version=1.1.7-hotfix

mod_id=blockzone
mod_name=BlockZone
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=dev.stya.blockzone
mod_authors=StyA
mod_description=Warzone game mode for FPSMatch.
